# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

resources:
 pipelines:
  - pipeline: buildContosoAir # identifier for the resource used in pipeline resource variables
    source: zeroshoes.ContosoAir # name of the pipeline that produces the artifact
    trigger:
     branches:
      include:
       - master

pool:
  #vmImage: ubuntu-latest
  name: default

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'e2a1ee9c-674a-4691-ba6a-2d6ef3ffe991'
    definition: '3'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure Connection'
    subscriptionId: 'cee46ee4-12c5-48e5-9055-3cca80c675b5'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourcegroup)'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.json'
    csmParametersFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.parameters.json'
    overrideParameters: '-p_environment $(web_environment) -p_site_prefix $(web_prefix) -p_site_web_name $(web_site)'
    deploymentMode: 'Incremental'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure Connection'
    appType: 'webApp'
    WebAppName: '$(web_prefix)-$(web_site)-$(web_environment)'
    packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
    
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
